import React from "react";
import { BsFacebook } from "react-icons/bs";
import { FcGoogle } from "react-icons/fc";
import { signIn } from "next-auth/react";
const Login = () => {
  return (
    <div className="grid grid-cols-2">
      <title>My FaceBook</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/avatar.jpg" />
      <div className="bg-primary h-screen grid place-items-center">
        <BsFacebook className="text-white text-[200px]" />
      </div>
      <div className="grid place-items-center bg-black">
        <div
          className="flex gap-4 bg-[#fff] p-4 px-4 items-center rounded-[6px] cursor-pointer"
          onClick={() => signIn("google")}
        >
          <FcGoogle className="text-[30px]" /> SignIn with Google
        </div>
      </div>
    </div>
  );
};
export default Login;
