import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import Feed from "../components/Feed";
import LeftSideBar from "../components/LeftSidebar";
import Login from "../components/Login";
import Navbar from "../components/Navbar";
import RightSidebar from "../components/RightSidebar";
export default function Home() {
  const { data: session } = useSession();
  if (!session) return <Login />;
  return (
    <>
      <Head>
        <title>My FaceBook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatar.jpg" />
      </Head>
      <main className="">
        <Navbar />
        <LeftSideBar />
        <RightSidebar />
        <Feed />
      </main>
    </>
  );
}
export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
